### ISSUE TITLE
High-level guide for newbies?

### ISSUE THREAD

**Issue by dr-diem** [arpa2/tlspool#11]
Hi,

I would like to install TLS Pool on my OS X environment in order to start testing interoperability with local software.

The INSTALL learning curve seems very steep; for example it is not clear to me whether PKCS #11 support is mandatory or not. What would be useful would be a higher-level preface that explained the install and setup steps in bullet-point form, prior to the in-depth details. This would help give new adopters a solid grounding in what they need to achieve - a set of compass points so to speak.

Cheers,

Ian

**Comment by vanrein** [comment]
Hell dr-diem,

> I would like to install TLS Pool on my OS X environment in order to start testing interoperability with local software

OK.  TLS Pool is programmed to be POSIX compliant, and I built it for FreeBSD in the past, so it should be doable.  I remember the only problem on FreeBSD being the autoconf stuff, but I can send you ./configure and **/Makefile.in if that problem still exists.

> The INSTALL learning curve seems very steep; for example it is not clear to me whether PKCS #11 support is mandatory or not What would be useful would be a higher-level preface that explained the install and setup steps in bullet-point form, prior to the in-depth details This would help give new adopters a solid grounding in what they need to achieve - a set of compass points so to speak

Yes, the learning curve is a bit steep, and for now more adapted to packagers than to homebrew use.  Also the management tools are still somewhat under development and one important aspect, namely validation of the remote peer's identity claim, has been delayed because we were still designing it.  As a matter of fact, I just started a branch for the latter.

It is partially due to the young state of the TLS Pool that it's all a bit steep to get into; we are scheduled to deliver on July 1st (our deliverable in return for some funding we got on the project).  The surrounding tools have made a giant step forwards last week, when I created a testdata/Makefile that demonstrates how to generate private keys and public credentials, for both X.509 and OpenPGP; this was a major stumbling block in getting it going in practical settings.

PKCS #11 is an intrinsic part of the design; it makes the private key handling method consistent but at the same time scalable between low-end architectures (using a software HSM), through simple USB crypto devices, all the way to high-end accellerated / replicated / distributed / rack-mounted HSM bastions.  So it's not like OpenSSL where you'd specify an engine and have the software version as a default; this is more like Mozilla, which has a PKCS #11 engine built in.  We'd advise using SoftHSMv2.

When you manage to build (and perhaps even package) the TLS Pool we would love to integrate your work on it, if you are willing to donate back to the project.  But you should take a warning that the project is still a bit raw on the edges.  Since you're doing something new that I can learn from, I'm interested in guiding you through the process.

On a sidenote: We just ported to Windows, and are moving that into cross-platform building with MXE.  I don't know if a similar approach is possible for Mac OS X; it would be great to be able to release Mac OS X packages as a matter of course, whenever we release a version.

I hope this helps!  And if not, let me know!

Best wishes,
 -Rick

**Comment by vanrein** [comment]
Please note that I checked in the autoconf output, so as to simplify at least that stage of the process.

**Comment by dr-diem** [comment]
Thanks Rick,

I guess what I was suggesting was that the documentation be altered to give a much higher-level overview of the steps; your answer certainly helps but I think it'd help me (and other adopters) focus their minds if such an installation overview were created.

Cheers,

Ian

**Comment by vanrein** [comment]
With higher-level you mean less-detailed, right?  I can already see the questions coming if we do that :) so for now it's going to have to be as detailed as it gets in the INSTALL file.  We are still developing on this one, and things might change.  And outdated documentation is the last thing we're waiting for I guess.  Thanks for the hint though, I will keep it in mind for a later phase.  FWIW, we are set to release around Juli 1st, 2016.  Until then I expect the TLS Pool to remain a bit rough around the edges.

**Comment by vanrein** [comment]
Oh,

And if you're looking for non-builder information, you can always visit the documentation on
http://tlspool.arpa2.net

-Rick

**Comment by dr-diem** [comment]
Understood, and thanks for keeping it in mind for a later stage.
