### ISSUE TITLE
tlspool platform independence

### ISSUE THREAD

**Issue by hfmanson** [arpa2/tlspool#70]
The current tlspool implementation relies heavily on posix file descriptors. These are also used in the tlspool API. Desirable is another tlspool API without the use of file descriptors and  instead use 'streams' with plain and encrypted traffic. Examples are OS'es without file descriptors and binding to higher level languages where file descriptors are not available, e.g. Java. In principle a tlspool ecosystem can be implemented with only TCP/IP sockets

Below an proposal of three new functions tlspool_starttls2, tlspool_read and tlspool_write for reading and writing unencrypted (plain) data

```
int tlspool_starttls2 (
    starttls_t *tlsdata,
    void *privdata, -> e.g. socket handle
    ssize_t read_encr(void *buf, size_t count), // read encrypted data from socket, called from tlspool when encrypted data is needed from socket
    ssize_t write_encr(const void *buf, size_t count), // write encrypted data to socket, called from tlspool when encrypted data is available to be written
    int (*namedconnect) (starttls_t *tlsdata, void *privdata)
);

ssize_t tlspool_read(void *buf, size_t count), // read unencrypted, sent to tlspool, returns when encrypted data has been decrypted 
ssize_t tlspool_write(const void *buf, size_t count), // write unencrypted, sent to tlspool 

```

This way tlspool can be implemented without the use of a Unix-domain socket. Instead a loopback TCP socket can be used instead

**Comment by vanrein** [comment]
This touches upon a number of existing thoughts, but from another angle.  In other words, this is interesting.

Instead of *replacing* the existing API call, we might consider making this an *alternative* interface to the TLS Pool.  That avoids changeover headaches.  Internally, the calls may use each other, depending on the underlying notion, in the most efficient manner possible.

It might be more in line with event-driven asynchronous programming to replace the active calls with callback registrations for the opposite directions; or to add those.  This works even better when the standard C library calls could be used here (so, when an integer leads the way, in some contexts holding a file descriptor but generally representing a callback identifier).

This could save use a common pattern, where we start a connection and continue to have to replicate data in both directions for as long as the connection over TLS persists.  This should be handled with `FORK` and `DETACH` options, but for the `https_proxy.py` this appears to be problematic (though that might be another problem) and there've been more examples that were less than perfect.

Interestingly, Python also proposes in [PEP 543](https://www.python.org/dev/peps/pep-0543/) to also standardise on a dual API, both socket interface and memory buffer interface.  (They do require filenames for keys and certificates though, and lack support for the abstraction that the TLS Pool provides.)

**Comment by vanrein** [comment]
*The current tlspool implementation relies heavily on posix file descriptors.*

Yes, the TLS Pool is inherently a POSIX application.  Windows is not even remotely at the same level of interest for the server platforms for which the TLS Pool was developed.

Even though "abstractions" might be constructed that capture the two platforms, it really is devestating to the readability of the code and, as a result, the ability to audit code.

Should we consider forking POSIX and Windows and keep them loosely feature-synchronised?  It would do a lot of good for the cleaniness both code base(s).

**Comment by vanrein** [comment]
Note that this problem is always going to stay when we add features.  Hence my considering about forking the two operating systems into clean code bases.  The asynchronous API is one more topic of contention.

Code should not be split-brained, and security code most certainly should not.  If the resulting code is difficult to audit because it mixes ideas, then should we continue to force them to live together?

It is worth noting that most of the TLS Pool is quite stable, and so a separation could be relatively painless.  After this has been done, it would be much easier to deal with Windows-specific desires, including #36 that wants to create a Windows Service but then follows a rather different concept than on POSIX systems.  If the two are so different, then maybe we should give in?

**Comment by vanrein** [comment]
If we decide to go this way, that is fork as two projects which share code whenever possible, we can use a few of the following advanced logic in git:

  * [cherry-pick](http://schacon.github.io/git/git-cherry-pick.html) to selectively pass "crocodile back bumps" on the `master` and `master-win` branches;
  * [merge-base](https://stackoverflow.com/questions/1549146/git-find-the-most-recent-common-ancestor-of-two-branches) to find the point where the `master` and `master-win` split up.

This is probably a better solution than our current practice of using `#ifdef` in code and configurations.  It frees both platforms to develop and mature on their own right, while still being able to pickup on projects that are useful to both.  The platforms can be developed and tested separately and, most importantly, audited separately (and doably!)

So this is my current proposal: to fork a `tlspool-win` and remove the `#ifdef` on both sides, just in the different ways.  That way, the best of both Worlds can be had and each developer can do what he does best.  Especially when we stay mindful of the common ground this should be workable?

**Comment by vanrein** [comment]
Just studied what [libev has to say](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#WIN32_PLATFORM_LIMITATIONS_AND_WORKA) based on its detailed insider knowledge of a portable API for event handling.  Clearly, it is a pipe dream to expect to resolve such vast differences in platform with a mere number of `#ifdef` patches; Windows is always going to be violently different.

This assures me that indeed, the Windows code needs to be able to live on its own, to be free and unconstrained to do things in One Microsoft Way.

**Comment by vanrein** [comment]
Forked the repository to [tlspool-windows](https://github.com/arpa2/tlspool-windows) to accommodate platform independence.
